BEGIN TRANSACTION;
DROP TABLE IF EXISTS "BOOKTEMP";
CREATE TABLE "BOOKTEMP" (
Word CHAR PRIMARY KEY  NOT NULL  UNIQUE , 
WordOri CHAR default "" , 

Meaning CHAR DEFAULT "", 
Desc CHAR DEFAULT "", 
 
Count INTEGER DEFAULT 0, 
Know INTEGER DEFAULT 0, 
ToMemorize INTEGER DEFAULT 0, 
Favorite INTEGER DEFAULT 0,

WordLevel1 INTEGER DEFAULT 999, 
WordLevel2 INTEGER DEFAULT 999, 
WordLevel3 INTEGER DEFAULT 999, 

Synonym CHAR DEFAULT "",
Antonym CHAR DEFAULT "",
Derived CHAR  DEFAULT "",  
WordType CHAR  DEFAULT "", 
Irreg INTEGER DEFAULT 0, 

Tag CHAR DEFAULT "",
 "InstalledWord" INTEGER DEFAULT 0, 

Know_Standard INTEGER DEFAULT 0, 
Know_Friend1 INTEGER DEFAULT 0, 
Know_Friend2 INTEGER DEFAULT 0, 
Know_Friend3 INTEGER DEFAULT 0, 

FirstAdd DATETIME DEFAULT  CURRENT_TIMESTAMP, 
FirstSee DATETIME, 
LastSee DATETIME, 

Pronounce CHAR DEFAULT "",
Pronounce1 CHAR DEFAULT "",
KnowPronounce INTEGER DEFAULT 3, 

CATEGORY1 INTEGER DEFAULT 0, 
CATEGORY2 INTEGER DEFAULT 0, 
CATEGORY3 INTEGER DEFAULT 0, 
CATEGORY4 INTEGER DEFAULT 0, 
CATEGORY5 INTEGER DEFAULT 0, 
CATEGORY6 INTEGER DEFAULT 0, 
CATEGORY7 INTEGER DEFAULT 0, 
CATEGORY8 INTEGER DEFAULT 0, 
CATEGORY9 INTEGER DEFAULT 0, 
RESERV1_INT INTEGER DEFAULT 0,
RESERV2_INT INTEGER DEFAULT 0,
RESERV3_INT INTEGER DEFAULT 0,
RESERV1_CHAR CHAR DEFAULT "",
RESERV2_CHAR CHAR DEFAULT "",
RESERV3_CHAR CHAR DEFAULT "",
RESERV1_BLOB BLOB,
RESERV2_BLOB BLOB,
RESERV3_BLOB BLOB,
WORDORDER INTEGER DEFAULT 0);
COMMIT;
